
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro', // Keep the intro page at the top
    {
      type: 'category',
      label: 'Module 1: Introduction & Setup',
      items: ['chapter1', 'chapter2'],
    },
    {
      type: 'category',
      label: 'Module 2: ROS 2 Core',
      items: ['chapter3', 'chapter4'],
    },
    {
      type: 'category',
      label: 'Module 3: Simulation',
      items: ['chapter5', 'chapter6'],
    },
    {
      type: 'category',
      label: 'Module 4: Navigation & Perception',
      items: ['chapter7', 'chapter8', 'chapter9'],
    },
    {
      type: 'category',
      label: 'Module 5: Voice & Hardware',
      items: ['chapter10', 'chapter11', 'chapter12'],
    },
    {
      type: 'category',
      label: 'Module 6: Capstone Project',
      items: ['chapter13', 'chapter14'],
    },
  ],
};

module.exports = sidebars;
